### ISSUE TITLE
使用 Travis 自动构建 Hexo depoly 到 GitHub 失败

### ISSUE THREAD

**Issue by OHLIA** [zthxxx/wiki-site#25]
你好，请教一下这个帖子 [使用 Travis 自动构建 Hexo 到 GitHub](https://blog.zthxxx.me/post/build-hexo-blog-by-travis-ci/#github-access-token) 的相关问题。

我直接复制你项目下的配置文件（去掉 `- gulp` 这步）和脚本，然后自己绑定了 Access Token，前面都过了，就是最后 `hexo deploy` 失败，步骤都没错，问题应该还是认证出了问题。

_config.yml 文件，我尝试修改过 repo 地址为 Https类, SSH类，修改 type 为 git 或者 https。都提示失败。

以下 log 是 type git, repo 地址 ssh类型出的结果。

```bash
$ hexo deploy
INFO  Deploying: git
INFO  Setting up Git deployment...
Initialized empty Git repository in /home/travis/build/OHLIA/Wiki-site/.deploy_git/.git/

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <>) not allowed
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: Spawn failed
    at ChildProcess.<anonymous> (/home/travis/build/OHLIA/Wiki-site/node_modules/hexo-util/lib/spawn.js:52:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
travis_time:end:1016f340:start=1566804459853647012,finish=1566804460828702185,duration=975055173
[0Ktravis_fold:end:after_success
[0K
Done. Your build exited with 0.
```

**Comment by OHLIA** [comment]
> 你好，请教一下这个帖子 [使用 Travis 自动构建 Hexo 到 GitHub](https://blog.zthxxx.me/post/build-hexo-blog-by-travis-ci/#github-access-token) 的相关问题。
> 
> 我直接复制你项目下的配置文件（去掉 `- gulp` 这步）和脚本，然后自己绑定了 Access Token，前面都过了，就是最后 `hexo deploy` 失败，步骤都没错，问题应该还是认证出了问题。
> 
> _config.yml 文件，我尝试修改过 repo 地址为 Https类, SSH类，修改 type 为 git 或者 https。都提示失败。
> 
> 以下 log 是 type git, repo 地址 ssh类型出的结果。
> 
> ```shell
> $ hexo deploy
> INFO  Deploying: git
> INFO  Setting up Git deployment...
> Initialized empty Git repository in /home/travis/build/OHLIA/Wiki-site/.deploy_git/.git/
> 
> *** Please tell me who you are.
> 
> Run
> 
>   git config --global user.email "you@example.com"
>   git config --global user.name "Your Name"
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.
> 
> fatal: empty ident name (for <>) not allowed
> FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
> Error: Spawn failed
>     at ChildProcess.<anonymous> (/home/travis/build/OHLIA/Wiki-site/node_modules/hexo-util/lib/spawn.js:52:19)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> travis_time:end:1016f340:start=1566804459853647012,finish=1566804460828702185,duration=975055173
> �[0Ktravis_fold:end:after_success
> �[0K
> Done. Your build exited with 0.
> ```

解决了，是环境变量没填入 travis-ci 里面。
